# syntax=docker/dockerfile:1
FROM python:3.13-slim-bookworm AS builder

COPY ./requirements.jupyter.txt ./requirements.txt

RUN python -m venv /venv && \
    /venv/bin/pip install --no-cache-dir -r requirements.txt


FROM python:3.13-slim-bookworm

RUN groupadd developers && useradd --no-user-group --no-log-init -g developers -m joe

COPY --from=builder /venv /venv

WORKDIR /home/joe

USER joe

ENV PATH="/venv/bin:$PATH"

EXPOSE 8888
ENTRYPOINT ["jupyter", "lab"]
CMD ["--port=8888", "--no-browser", "--ip=0.0.0.0"]
